(body (h2 "title: Javascript sucks.")
 (h1 "Table of Contents")
 (ol (li (p "PLEASE STOP USING JAVASCRIPT")
         (ol
          (li "Reasons to stop using JavaScript")))
     (li "Can " "!" "= Should")
     (li "What in the hell is a build tool?!")
     (li "THIS WEBSITE USES JAVASCRIPT"))
 (h1 "PLEASE STOP USING JAVASCRIPT")
 (h2 "Reasons to stop using JavaScript")
 (ol (li (p "Because I said so."))
     (li (p "More reasons are left as an exercise to the reader.")))
 (h1 "Can " "!" "= Should")
 (p "Just because you " (strong "CAN") " use javascript doesn't mean you "
    (strong "SHOULD!!"))
 (p "NO, your personal blog doesn't need REACT JS!")
 (h1 "What in the hell is a build tool?!")
 (p (strong (strong "WHY")) " do I need a build tool to use basically any javascript??")
 (h1 "THIS WEBSITE USES JAVASCRIPT")
 (p "And it will probably crash by the time you're done reading!")
 (script "setTimeout(() => {let i = 0;let a = [];while (1) {console.log('JS BAD');a[i++] = 69;}}, 1000)"))
