name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sohamg/emacs
    steps:
      - name: Check out
        uses: actions/checkout@v1
        
      - name: Build the site
        run: ./build.sh

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public
          git-config-name: "gh-runner"
          git-config-email: "gh-runner@example.com"
